language: swift
osx_image: xcode9.2
install:
- gem install xcpretty
- gem install fastlane -NV
- gem install cocoapods --pre
script:
- pod install
- xcrun simctl list
- set -o pipefail && xcodebuild -workspace DocuTest.xcworkspace -scheme 'DocuTest' -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (2nd generation)' | xcpretty -c
- fastlane screenshots