# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-and-test:
    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"
    working_directory: /Users/distiller/project
    environment:
      # FL_OUTPUT_DIR: /Users/distiller/project/output
      FASTLANE_LANE: screenshots
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: mkdir $FL_OUTPUT_DIR
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      # - run:
      #     command: cp $FL_OUTPUT_DIR/scan/report.junit $FL_OUTPUT_DIR/scan/results.xml
      #     when: always
      # - store_artifacts:
      #     path: /Users/distiller/project/output
      - store_artifacts:
          path: /Users/distiller/project/fastlane/screenshots
          destination: screenshots

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
